import type { Metadata } from "next";
import { Sora, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/app/context/UserContext";
import { Toaster } from "react-hot-toast";
import { Providers } from "./providers";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GK Fitness",
  description: "Generated by create next app",
  icons: {
    icon: "/512x512 2.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sora.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <UserProvider>
            <Toaster 
              position="top-right" 
              toastOptions={{
                style: {
                  background: '#14151A',
                  color: '#fff',
                  border: '1px solid rgba(255,255,255,0.05)'
                },
                success: {
                  iconTheme: { primary: '#D4FF32', secondary: '#000' }
                }
              }} 
            />
            {children}
          </UserProvider>
        </Providers>
      </body>
    </html>
  );
}
